# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='blog/')),
                ('header', models.CharField(max_length=80)),
                ('summary', models.TextField()),
            ],
        ),
    ]
