# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Image', models.ImageField(default='default.png', upload_to='Banner_image')),
            ],
        ),
    ]
