# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-14 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('Create', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField()),
            ],
        ),
    ]
